In [1]:
# Import Numpy Library
import numpy as np

In [6]:
# created class Employee
class Employee():
    # create data members to keep count of employee count and list of salaries
    emp_count = 0

    # constructor to initilize the variables
    def __init__(self,name,family,salary,department):
        self.name = name,
        self.family = family,
        self.salary = salary,
        self.department = department,
        Employee.emp_count += 1

    # funtion to return average of salary
    def avg_salary(employees:list):
        # calculate salaries average
        salaries_list = [emp.salary[0] for emp in employees]
        # print(emp.salary[0] for emp in employees)
        avg_sal = sum(salaries_list)/Employee.emp_count     # method 1 : generic
        # avg_sal = np.mean(salaries_list)                      # method 2 : using numpy
        return avg_sal

# created FullTimeEmployee class and inherit the properties from Employee class
class FullTimeEmployee(Employee):
    def __init__(self,name,family,salary,department):
        # calling parent class constructor
        super().__init__(name,family,salary,department)

employees = []
employees.append(Employee("Naveen","Indluru",40000,"analytics"))
employees.append(Employee("Anvesh","Kalikiri",74000,"CTO"))

employees.append(FullTimeEmployee("Naveen Reddy","Indluru",50000,"data science"))
employees.append(FullTimeEmployee("Jagadeesh","Kethu",84000,"data analytics"))


print("using employee class",Employee.avg_salary(employees))
print("using fulltime employee class",FullTimeEmployee.avg_salary(employees))

using employee class 62000.0
using fulltime employee class 62000.0


In [4]:
arr = np.random.uniform(1,20,20) # created a random vector of size 20 in the range of 1 - 20.
arr = arr.reshape(4,5) # reshaped the vector to array of (4,5) shape

In [5]:
# Task : replace the max in each row by 0 (axis = 1)

# print array before replacement
print("Array before :\n\n",arr,end="\n\n\n")

# get max elements of each row and reshape it
each_row_max = np.max(arr,axis = 1).reshape(-1,1)

arr[arr == each_row_max] = 1

# print array after replacement
print("Array after replace the max element of each row with 1: \n\n", arr)

Array before :

 [[ 7.33128224  5.56995393  9.0312551   7.45693199  8.21054117]
 [ 5.97029035 14.19808821 16.83025735  7.03973153 15.09887243]
 [ 4.63396206 15.30745409  6.34197445 13.009619    2.73947355]
 [12.35704378 18.6223202   4.73015523 14.45032106  4.39796606]]


Array after replace the max element of each row with 1: 

 [[ 7.33128224  5.56995393  1.          7.45693199  8.21054117]
 [ 5.97029035 14.19808821  1.          7.03973153 15.09887243]
 [ 4.63396206  1.          6.34197445 13.009619    2.73947355]
 [12.35704378  1.          4.73015523 14.45032106  4.39796606]]
